# Generated by Django 5.2.5 on 2025-08-29 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_clientcompany_servicetype_skill_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("transport", "Transportation"),
                    ("materials", "Materials"),
                    ("meals", "Meals"),
                    ("accommodation", "Accommodation"),
                    ("tools", "Tools & Equipment"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date_incurred",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
