# Generated by Django 5.2.5 on 2025-08-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_job_last_updated_job_updated_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientcompany",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clientcompany",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="clientcompany",
            name="industry",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="clientcompany",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="clientcompany",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
