# Generated by Django 5.2.5 on 2025-08-31 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_clientcompany_address_and_more"),
        ("accounts", "0005_jobreport"),
    ]

    operations = []
