# docker-compose.prod.yml
version: "3.8"
services:
  web:
    image: ${DOCKER_HUB_REPO}:${IMAGE_TAG:-latest}
    restart: unless-stopped
    env_file:
      - .env.production
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  static_volume:
  media_volume:
