name: CI/CD Pipeline

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Build and Push to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/mgmt_v2:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # Deploy to EC2
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/mgmt_v2:latest

            # Pull latest image
            docker pull $IMAGE_NAME

            # Stop and remove old container
            docker stop mgmt_app || true
            docker rm mgmt_app || true

            # Run migrations before starting container
            docker run --rm \
              -e DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}" \
              -e ALLOWED_HOSTS="13.62.67.73" \
              $IMAGE_NAME python manage.py migrate

            # Start new container
            docker run -d -p 8000:8000 \
              -e DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}" \
              -e ALLOWED_HOSTS="13.62.67.73" \
              --name mgmt_app \
              $IMAGE_NAME
