name: CI/CD Pipeline

on:
  push:
    branches: [ main ]   # Change if you want another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Build and Push to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/mgmt_v2:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # Deploy to EC2
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/mgmt_v2:latest
            docker pull $IMAGE_NAME
            docker stop mgmt_app || true
            docker rm mgmt_app || true
            docker run -d -p 8000:8000 --name mgmt_app $IMAGE_NAME
